apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: housing-price-16092022-v3
  namespace: dev
spec:
  predictors:
  - graph:
      envSecretRefName: mlopsplatformdemo-secret
      implementation: SKLEARN_CUSTOM_SERVER
      modelUri: azureblob:model-artifacts/housing-price-16092022-v3/dev/4
      name: housing-price-16092022-v3-graph
      parameters:
      - name: method
        type: STRING
        value: predict
      serviceAccountName: myserviceaccount
      storageInitializerImage: seldonio/rclone-storage-initializer:1.15.0-dev
    name: default
    replicas: 1
