apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: model-6481a9b3f130fad682520fb2
  namespace: stag
spec:
  predictors:
  - graph:
      envSecretRefName: sa-access-secret
      implementation: SKLEARN_CUSTOM_SERVER
      modelUri: azureblob:model-artifacts/model-6481a9b3f130fad682520fb2/stag/1
      name: model-6481a9b3f130fad682520fb2-graph
      parameters:
      - name: method
        type: STRING
        value: predict
      serviceAccountName: myserviceaccount
      storageInitializerImage: seldonio/rclone-storage-initializer:1.15.0-dev
    name: default
    replicas: 1
