apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: model-64d24ba47329cc6f1ccd24a6
  namespace: dev
spec:
  predictors:
  - graph:
      envSecretRefName: sa-access-secret
      implementation: SKLEARN_CUSTOM_SERVER
      modelUri: azureblob:model-artifacts/model-64d24ba47329cc6f1ccd24a6/dev/1
      name: model-64d24ba47329cc6f1ccd24a6-graph
      parameters:
      - name: method
        type: STRING
        value: predict
      serviceAccountName: myserviceaccount
      storageInitializerImage: seldonio/rclone-storage-initializer:1.15.0-dev
    name: default
    replicas: 1
