apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: model-64a47d4da3b03a94521913a7
  namespace: dev
spec:
  predictors:
  - graph:
      envSecretRefName: sa-access-secret
      implementation: SKLEARN_CUSTOM_SERVER
      modelUri: azureblob:model-artifacts/model-64a47d4da3b03a94521913a7/dev/6
      name: model-64a47d4da3b03a94521913a7-graph
      parameters:
      - name: method
        type: STRING
        value: predict
      serviceAccountName: myserviceaccount
      storageInitializerImage: seldonio/rclone-storage-initializer:1.15.0-dev
    name: default
    replicas: 1
