apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: newmodelseshdeltafix_eveningshopper10_3847463872c44ea0b0325a3fcf1eb25b
  namespace: dev
spec:
  predictors:
  - graph:
      envSecretRefName: mlopsplatformdemo-secret
      implementation: SKLEARN_CUSTOM_SERVER
      modelUri: azureblob:model-artifacts/newmodelseshdeltafix_eveningshopper10_3847463872c44ea0b0325a3fcf1eb25b/dev/1
      name: newmodelseshdeltafix_eveningshopper10_3847463872c44ea0b0325a3fcf1eb25b-graph
      parameters:
      - name: method
        type: STRING
        value: predict
      serviceAccountName: myserviceaccount
      storageInitializerImage: seldonio/rclone-storage-initializer:1.15.0-dev
    name: default
    replicas: 1
