apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: model-648165915b8ce08b50dd0dd0
  namespace: dev
spec:
  predictors:
  - graph:
      envSecretRefName: sa-access-secret
      implementation: SKLEARN_CUSTOM_SERVER
      modelUri: azureblob:model-artifacts/model-648165915b8ce08b50dd0dd0/dev/11
      name: model-648165915b8ce08b50dd0dd0-graph
      parameters:
      - name: method
        type: STRING
        value: predict
      serviceAccountName: myserviceaccount
      storageInitializerImage: seldonio/rclone-storage-initializer:1.15.0-dev
    name: default
    replicas: 1
