apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: random_forest_night_shopper_4_ceb46c342ee54d02a9d95f22daacd0ea_e
  namespace: dev
spec:
  predictors:
  - graph:
      envSecretRefName: mlopsplatformdemo-secret
      implementation: SKLEARN_CUSTOM_SERVER
      modelUri: azureblob:model-artifacts/random_forest_night_shopper_4_ceb46c342ee54d02a9d95f22daacd0ea_e/dev/1
      name: random_forest_night_shopper_4_ceb46c342ee54d02a9d95f22daacd0ea_e-graph
      parameters:
      - name: method
        type: STRING
        value: predict
      serviceAccountName: myserviceaccount
      storageInitializerImage: seldonio/rclone-storage-initializer:1.15.0-dev
    name: default
    replicas: 1
