apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: brand-dt
  namespace: prod
spec:
  predictors:
  - graph:
      envSecretRefName: mlopsplatformdemo-secret
      implementation: SKLEARN_CUSTOM_SERVER
      modelUri: azureblob:model-artifacts/brand-dt/prod/4
      name: brand-dt-graph
      parameters:
      - name: method
        type: STRING
        value: predict
      serviceAccountName: myserviceaccount
      storageInitializerImage: seldonio/rclone-storage-initializer:1.15.0-dev
    name: default
    replicas: 1
