general_configs: 
  sdk_session_id: 
    dev: 34dc9e5e023b4cf3bf68695433fa5b11
    uat: 7e79fc0b5b1e4cadbe40141d9f1b9af3
    prod: 64ec92d6117247877965d152
  tracking_env: uat
  tracking_url : mlcoreuatv2pg21.azurewebsites.net


data_engineering_ft:
  datalake_configs:
    input_tables:
      source_1: 
        catalog_name: mlcore_dev
        schema: retail_price_sdk_flow
        table: retail_prices_ft
        primary_keys: index
    output_tables:
      output_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1203
        table: retail_prices_1203_ft
        primary_keys: index
  storage_configs:
    cloud_provider: databricks_uc
    params:
      metastore: null
      catalog_name: mlcore_dev
      schema_name: mlcore
      volume_name: mlcore_volume
  is_scheduled: false
  batch_size: 500
  cron_job_schedule: "0 */30 * ? * *"

data_engineering_gt:
  datalake_configs:
    input_tables:
      source_1: 
        catalog_name: mlcore_dev
        schema: retail_price_sdk_flow
        table: retail_prices_gt
        primary_keys: index
    output_tables:
      output_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1203
        table: retail_prices_1203_gt
        primary_keys: index
  storage_configs:
    cloud_provider: databricks_uc
    params:
      metastore: null
      catalog_name: mlcore_dev
      schema_name: mlcore
      volume_name: mlcore_volume
  is_scheduled: false
  batch_size: 500
  cron_job_schedule: "0 */30 * ? * *"

feature_pipelines_ft:
  datalake_configs:
    input_tables:
      input_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1203
        table: retail_prices_1203_ft
        primary_keys: index
    output_tables:
      output_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1203
        table: Transformed_retail_prices_1203_ft
        primary_keys: index
  storage_configs:
    cloud_provider: databricks_uc
    params:
      metastore: null
      catalog_name: mlcore_dev
      schema_name: mlcore
      volume_name: mlcore_volume
  is_scheduled: false

feature_pipelines_gt:
  datalake_configs:
    input_tables: 
      input_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1203
        table: retail_prices_1203_gt
        primary_keys: index
    output_tables: 
      output_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1203
        table: Transformed_retail_prices_1203_gt
        primary_keys: index
  storage_configs:
    cloud_provider: databricks_uc
    params:
      metastore: null
      catalog_name: mlcore_dev
      schema_name: mlcore
      volume_name: mlcore_volume
  is_scheduled: false

train:
  datalake_configs:
    input_tables: 
      input_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1203
        table: Transformed_retail_prices_1203_ft
        primary_keys: index
      input_2:
        catalog_name: mlcore_dev
        schema: retail_prices_1203
        table: Transformed_retail_prices_1203_gt
        primary_keys: index
    output_tables: 
      output_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1203
        table: train_output_retail_prices_1203
        primary_keys: index
  model_configs:
    registry_platform: databricks
    model_registry: mlflow
    unity_catalog: "yes"
    model_registry_params:
      catalog_name: mlcore_dev
      schema_name: retail_prices_1203
    model_params:      
      model_name: model_retail_prices_1203
  storage_configs:
    cloud_provider: databricks_uc
    params:
      metastore: null
      catalog_name: mlcore_dev
      schema_name: mlcore
      volume_name: mlcore_volume
  test_size: 0.2
  feature_columns:
    - product_category_name
    - freight_price
    - unit_price
    - product_name_lenght
    - product_description_lenght
    - product_photos_qty
    - product_weight_g
    - product_score
    - customers
    - weekday
    - weekend
    - holiday
    - month
    - year
    - s
    - comp_1
    - comp_2
    - comp_3
    - lag_price
  date_column:
  target_columns:
    - units_sold
  horizon: 7
  frequency: 'D'
  is_scheduled: false
  hyperparameter_tuning:
    max_evaluations : 2
    primary_metric : r2
    search_range :
      seasonality_prior_scale : 
        - 0.1
        - 10
      changepoint_prior_scale : 
        - 0.01
        - 0.5
      seasonality_mode : 
        - multiplicative
        - additive
    stop_early : false
    run_parallel : false
data_prep_deployment_ft:
  datalake_configs:
    input_tables:
      input_1:
        catalog_name: mlcore_dev
        schema: retail_price_sdk_flow
        table: retail_prices_1203_ft
        primary_keys: index
    output_tables:
      output_1:
        catalog_name: mlcore_dev
        schema: retail_price_sdk_flow
        table: dpd_retail_prices_1203_ft
        primary_keys: index  
  storage_configs:
    cloud_provider: databricks_uc
    params:
      metastore: null
      catalog_name: mlcore_dev
      schema_name: mlcore
      volume_name: mlcore_volume
  is_scheduled: true
  batch_size: 100
  cron_job_schedule: "0 */30 * ? * *"

data_prep_deployment_gt:
  datalake_configs:
    input_tables: 
      input_1:
        catalog_name: mlcore_dev
        schema: retail_price_sdk_flow
        table: retail_prices_1203_gt
        primary_keys: index
    output_tables: 
      output_1:
        catalog_name: mlcore_dev
        schema: retail_price_sdk_flow
        table: dpd_retail_prices_1203_gt
        primary_keys: index  
  storage_configs:
    cloud_provider: databricks_uc
    params:
      metastore: null
      catalog_name: mlcore_dev
      schema_name: mlcore
      volume_name: mlcore_volume
  is_scheduled: true
  batch_size: 100
  cron_job_schedule: "0 */30 * ? * *"

inference:
  datalake_configs:
    input_tables: 
      input_1:
        catalog_name: mlcore_dev
        schema: retail_price_sdk_flow
        table: dpd_retail_prices_1203_ft
        primary_keys: index
      input_2:
        catalog_name: mlcore_dev
        schema: retail_price_sdk_flow
        table: dpd_retail_prices_1203_gt
        primary_keys: index
    output_tables: 
      output_1:
        catalog_name: mlcore_dev
        schema: retail_price_sdk_flow
        table: inference_output_retail_prices_1203
        primary_keys: index
  model_configs:
    use_latest_version: true
  is_scheduled: true
  batch_size: 100
  cron_job_schedule: "0 */30 * ? * *"
