general_configs: 
  sdk_session_id:
    dev: 3979d2b155be480f8011aef42f9c8668
    uat: d98eddaad3ef4f77a3bf308fcca9692a
    prod: 64ec92d6117247877965d152
  tracking_env: dev
  tracking_url : mlcagentflowdevbackend.azurewebsites.net


data_engineering_ft:
  datalake_configs:
    input_tables:
      source_1: 
        catalog_name: mlcore_dev
        schema: retail_price_sdk_flow
        table: retail_prices_raw
        primary_keys: index
    output_tables:
      output_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1610_v4
        table: retail_prices_1610_v4_ft
        primary_keys: index
  storage_configs:
    cloud_provider: databricks_uc
    params:
      metastore: null
      catalog_name: mlcore_dev
      schema_name: mlcore
      volume_name: mlcore_volume
  is_scheduled: false
  batch_size: 500
  cron_job_schedule: "0 */30 * ? * *"

data_engineering_gt:
  datalake_configs:
    input_tables:
      source_1: 
        catalog_name: mlcore_dev
        schema: retail_price_sdk_flow
        table: retail_prices_raw
        primary_keys: index
    output_tables:
      output_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1610_v4
        table: retail_prices_1610_v4_gt
        primary_keys: index
  storage_configs:
    cloud_provider: databricks_uc
    params:
      metastore: null
      catalog_name: mlcore_dev
      schema_name: mlcore
      volume_name: mlcore_volume
  is_scheduled: false
  batch_size: 500
  cron_job_schedule: "0 */30 * ? * *"

feature_pipelines_ft:
  datalake_configs:
    input_tables:
      input_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1610_v4
        table: retail_prices_1610_v4_ft
        primary_keys: index
    output_tables:
      output_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1610_v4
        table: Transformed_retail_prices_1610_v4_ft
        primary_keys: index
  storage_configs:
    cloud_provider: databricks_uc
    params:
      metastore: null
      catalog_name: mlcore_dev
      schema_name: mlcore
      volume_name: mlcore_volume
  is_scheduled: false

feature_pipelines_gt:
  datalake_configs:
    input_tables: 
      input_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1610_v4
        table: retail_prices_1610_v4_gt
        primary_keys: index
    output_tables: 
      output_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1610_v4
        table: Transformed_retail_prices_1610_v4_gt
        primary_keys: index
  storage_configs:
    cloud_provider: databricks_uc
    params:
      metastore: null
      catalog_name: mlcore_dev
      schema_name: mlcore
      volume_name: mlcore_volume
  is_scheduled: false

train:
  datalake_configs:
    input_tables: 
      input_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1610_v4
        table: Transformed_retail_prices_1610_v4_ft
        primary_keys: index
      input_2:
        catalog_name: mlcore_dev
        schema: retail_prices_1610_v4
        table: Transformed_retail_prices_1610_v4_gt
        primary_keys: index
    output_tables: 
      output_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1610_v4
        table: train_output_retail_prices_1610_v4
        primary_keys: index
  model_configs:
    registry_platform: databricks
    model_registry: mlflow
    unity_catalog: "yes"
    model_registry_params:
      catalog_name: mlcore_dev
      schema_name: retail_prices_1610_v4
    model_params:      
      model_name: model_retail_prices_1610_v4
  storage_configs:
    cloud_provider: databricks_uc
    params:
      metastore: null
      catalog_name: mlcore_dev
      schema_name: mlcore
      volume_name: mlcore_volume
  test_size: 0.2
  feature_columns:
    - product_category_name
    - freight_price
    - unit_price
    - product_name_lenght
    - product_description_lenght
    - product_photos_qty
    - product_weight_g
    - product_score
    - customers
    - weekday
    - weekend
    - holiday
    - month
    - year
    - s
    - comp_1
    - comp_2
    - comp_3
    - lag_price
    - date
  date_column:
  target_columns:
    - units_sold
  is_scheduled: false
data_prep_deployment_ft:
  datalake_configs:
    input_tables:
      input_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1610_v4
        table: retail_prices_1610_v4_ft
        primary_keys: index
    output_tables:
      output_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1610_v4
        table: dpd_retail_prices_1610_v4_ft
        primary_keys: index  
  storage_configs:
    cloud_provider: databricks_uc
    params:
      metastore: null
      catalog_name: mlcore_dev
      schema_name: mlcore
      volume_name: mlcore_volume
  is_scheduled: true
  batch_size: 200
  cron_job_schedule: "0 */30 * ? * *"

data_prep_deployment_gt:
  datalake_configs:
    input_tables: 
      input_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1610_v4
        table: retail_prices_1610_v4_gt
        primary_keys: index
    output_tables: 
      output_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1610_v4
        table: dpd_retail_prices_1610_v4_gt
        primary_keys: index  
  storage_configs:
    cloud_provider: databricks_uc
    params:
      metastore: null
      catalog_name: mlcore_dev
      schema_name: mlcore
      volume_name: mlcore_volume
  is_scheduled: true
  batch_size: 200
  cron_job_schedule: "0 */30 * ? * *"

inference:
  datalake_configs:
    input_tables: 
      input_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1610_v4
        table: dpd_retail_prices_1610_v4_ft
        primary_keys: index
      input_2:
        catalog_name: mlcore_dev
        schema: retail_prices_1610_v4
        table: dpd_retail_prices_1610_v4_gt
        primary_keys: index
    output_tables: 
      output_1:
        catalog_name: mlcore_dev
        schema: retail_prices_1610_v4
        table: inference_output_retail_prices_1610_v4
        primary_keys: index
  model_configs:
    use_latest_version: true
  is_scheduled: true
  batch_size: 100
  cron_job_schedule: "0 */30 * ? * *"
