apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: model-649b29bf0d5a0fac6e8ef5dc
  namespace: dev
spec:
  predictors:
  - graph:
      envSecretRefName: sa-access-secret
      implementation: SKLEARN_CUSTOM_SERVER
      modelUri: azureblob:model-artifacts/model-649b29bf0d5a0fac6e8ef5dc/dev/1
      name: model-649b29bf0d5a0fac6e8ef5dc-graph
      parameters:
      - name: method
        type: STRING
        value: predict
      serviceAccountName: myserviceaccount
      storageInitializerImage: seldonio/rclone-storage-initializer:1.15.0-dev
    name: default
    replicas: 1
