apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: model-c310f946d2224b88bc5bf093c3332b26
  namespace: dev
spec:
  predictors:
  - graph:
      envSecretRefName: sa-access-secret
      implementation: SKLEARN_CUSTOM_SERVER
      modelUri: azureblob:model-artifacts/model-c310f946d2224b88bc5bf093c3332b26/dev/3
      name: model-c310f946d2224b88bc5bf093c3332b26-graph
      parameters:
      - name: method
        type: STRING
        value: predict
      serviceAccountName: myserviceaccount
      storageInitializerImage: seldonio/rclone-storage-initializer:1.15.0-dev
    name: default
    replicas: 1
