apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: brand-17-rf-v4
  namespace: dev
spec:
  predictors:
  - graph:
      envSecretRefName: mlopsplatformdemo-secret
      implementation: SKLEARN_CUSTOM_SERVER
      modelUri: azureblob:model-artifacts/brand-17-rf-v4/dev/1
      name: brand-17-rf-v4-graph
      parameters:
      - name: method
        type: STRING
        value: predict
      serviceAccountName: myserviceaccount
      storageInitializerImage: seldonio/rclone-storage-initializer:1.15.0-dev
    name: default
    replicas: 1
