apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: brand17-unitsales-rf
  namespace: stage
spec:
  predictors:
  - graph:
      envSecretRefName: mlopsplatformdemo-secret
      implementation: SKLEARN_CUSTOM_SERVER
      modelUri: azureblob:model-artifacts/brand17-unitsales-rf/stage/2
      name: brand17-unitsales-rf-graph
      parameters:
      - name: method
        type: STRING
        value: predict
      serviceAccountName: myserviceaccount
      storageInitializerImage: seldonio/rclone-storage-initializer:1.15.0-dev
    name: default
    replicas: 1
