apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: $(parameters.model-artifact-id)
  namespace: dev
spec:
  predictors:
  - graph:
      envSecretRefName: mlopsplatformdemo-secret
      implementation: SKLEARN_CUSTOM_SERVER
      modelUri: azureblob:model-artifacts/$(parameters.model-artifact-id)/dev/1
      name: $(parameters.model-artifact-id)-graph
      parameters:
      - name: method
        type: STRING
        value: predict
      serviceAccountName: myserviceaccount
      storageInitializerImage: seldonio/rclone-storage-initializer:1.15.0-dev
    name: default
    replicas: 1
